"""incluyendo precios por mayoreo

Revision ID: 7977ea20cfd5
Revises: 0cc892c8dc28
Create Date: 2026-01-06 19:53:47.391790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7977ea20cfd5'
down_revision = '0cc892c8dc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'min_qty', name='uq_price_tier_product_minqty')
    )
    with op.batch_alter_table('price_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_tiers_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_tiers_product_id'))

    op.drop_table('price_tiers')
    # ### end Alembic commands ###
