"""eliminando modulo de pagos

Revision ID: 871034705618
Revises: af1654cc8224
Create Date: 2026-01-12 09:07:18.897370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871034705618'
down_revision = 'af1654cc8224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('reference', sa.VARCHAR(length=120), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###
